name: RecoEnv
channels:
  - defaults
  - conda-forge
dependencies: 
  - python=3.8
  - pip
  - numpy
  - cython
  - scipy
  - h5py
  - matplotlib
  - scikit-image
  - ipykernel
  - Cython 
  - Pillow 
  - wget 
  - six  
  - pip:
    - zenodo_get
    - ismrmrd
    - deprecation
    - git+https://github.com/ismrmrd/ismrmrd-python-tools.git@master#egg=ismrmrd-python-tools

  
    
